const words = [
  { word: "apple", hint: "Juicy red fruit" },
  { word: "banana", hint: "Yellow tropical fruit" },
  { word: "cat", hint: "Furry pet animal" },
  { word: "dog", hint: "Loyal barking companion" },
  { word: "elephant", hint: "Large tusked mammal" },
  { word: "frog", hint: "Amphibian with hops" },
  { word: "guitar", hint: "Stringed musical instrument" },
  { word: "house", hint: "Place of residence" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "jungle", hint: "Thick tropical forest" },
  { word: "koala", hint: "Australian marsupial" },
  { word: "lion", hint: "King of the jungle" },
  { word: "mountain", hint: "Tall natural elevation" },
  { word: "nurse", hint: "Medical caregiver" },
  { word: "ocean", hint: "Vast body of water" },
  { word: "pizza", hint: "Delicious Italian dish" },
  { word: "queen", hint: "Female ruler" },
  { word: "rainbow", hint: "Colorful arc in the sky" },
  { word: "sunflower", hint: "Yellow flower that follows the sun" },
  { word: "tiger", hint: "Striped feline predator" },
  { word: "umbrella", hint: "Protective portable canopy" },
  { word: "volcano", hint: "Mountain that erupts" },
  { word: "waterfall", hint: "Falling water from a height" },
  { word: "xylophone", hint: "Musical instrument with wooden bars" },
  { word: "yoga", hint: "Physical and mental discipline" },
  { word: "zebra", hint: "Striped African mammal" },
  { word: "airplane", hint: "Aircraft for air travel" },
  { word: "butterfly", hint: "Colorful flying insect" },
  { word: "chocolate", hint: "Sweet treat made from cocoa" },
  { word: "dragon", hint: "Mythical fire-breathing creature" },
  { word: "elephant", hint: "Large tusked mammal" },
  { word: "fireworks", hint: "Explosive pyrotechnic display" },
  { word: "giraffe", hint: "Tall African mammal with long neck" },
  { word: "hamburger", hint: "Grilled meat in a bun" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "jacket", hint: "Outerwear garment" },
  { word: "kangaroo", hint: "Australian marsupial with a pouch" },
  { word: "lemon", hint: "Yellow citrus fruit" },
  { word: "moon", hint: "Natural satellite of Earth" },
  { word: "night", hint: "Time between sunset and sunrise" },
  { word: "octopus", hint: "Marine creature with tentacles" },
  { word: "piano", hint: "Keyboard musical instrument" },
  { word: "queen", hint: "Female ruler" },
  { word: "rain", hint: "Water falling from the sky" },
  { word: "sun", hint: "Star that provides light and heat" },
  { word: "tree", hint: "Tall woody plant" },
  { word: "unicorn", hint: "Mythical horse with a horn" },
  { word: "volleyball", hint: "Team sport played with a ball" },
  { word: "watermelon", hint: "Juicy fruit with red flesh" },
  { word: "xylophone", hint: "Musical instrument with wooden bars" },
  { word: "yacht", hint: "Luxury boat for leisure" },
  { word: "zeppelin", hint: "Airship with a rigid structure" },
  { word: "anchor", hint: "Heavy object to keep a ship in place" },
  { word: "balloon", hint: "Inflatable object filled with gas" },
  { word: "cloud", hint: "Visible mass of water droplets" },
  { word: "dolphin", hint: "Marine mammal known for its intelligence" },
  { word: "earring", hint: "Piece of jewelry worn on the ear" },
  { word: "fireplace", hint: "Structure for containing a fire indoors" },
  { word: "garden", hint: "Outdoor space for cultivating plants" },
  { word: "helicopter", hint: "Rotorcraft that can take off and land vertically" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "jigsaw", hint: "Puzzle with irregularly shaped pieces" },
  { word: "kite", hint: "Toy flown in the wind" },
  { word: "lighthouse", hint: "Tower with a bright light to guide ships" },
  { word: "moonlight", hint: "Light from the moon" },
  { word: "notebook", hint: "Book with blank pages for writing" },
  { word: "orchid", hint: "Colorful flowering plant" },
  { word: "parrot", hint: "Colorful talking bird" },
  { word: "quilt", hint: "Bed covering made of stitched fabric" },
  { word: "raincoat", hint: "Waterproof coat for rainy weather" },
  { word: "sailboat", hint: "Boat with sails for propulsion" },
  { word: "telescope", hint: "Optical instrument for viewing distant objects" },
  { word: "umbrella", hint: "Canopy to protect from rain or sun" },
  { word: "violin", hint: "Stringed musical instrument" },
  { word: "whale", hint: "Large marine mammal" },
  { word: "xylophone", hint: "Musical instrument with wooden bars" },
  { word: "yacht", hint: "Luxury boat for leisure" },
  { word: "zebra", hint: "African mammal with black and white stripes" },
];
  export default words

